# version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: managment
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
